// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.option(__t.string()),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
  pitch: __t.f32(),
  roll: __t.f32(),
  hue: __t.f32(),
  alive: __t.bool(),
  inFormation: __t.bool().name("in_formation"),
  flockSize: __t.i32().name("flock_size"),
  survivalTicks: __t.i32().name("survival_ticks"),
  online: __t.bool(),
  lastUpdate: __t.timestamp().name("last_update"),
});
