// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Hawk = __t.object("Hawk", {
  id: __t.u32(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  targetIdentity: __t.option(__t.identity()),
  tactic: __t.string(),
  thought: __t.string(),
  speed: __t.f32(),
  updatedAt: __t.timestamp(),
});
export type Hawk = __Infer<typeof Hawk>;

export const KillFeed = __t.object("KillFeed", {
  id: __t.u64(),
  victimName: __t.string(),
  thought: __t.string(),
  at: __t.timestamp(),
});
export type KillFeed = __Infer<typeof KillFeed>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.option(__t.string()),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
  pitch: __t.f32(),
  roll: __t.f32(),
  hue: __t.f32(),
  alive: __t.bool(),
  inFormation: __t.bool(),
  flockSize: __t.i32(),
  survivalTicks: __t.i32(),
  online: __t.bool(),
  lastUpdate: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const TickSchedule = __t.object("TickSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickSchedule = __Infer<typeof TickSchedule>;

export const World = __t.object("World", {
  id: __t.u32(),
  tickCount: __t.u64(),
  huntActive: __t.bool(),
});
export type World = __Infer<typeof World>;

