// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import JoinGameReducer from "../join_game_reducer";
import RespawnReducer from "../respawn_reducer";
import SetHawkIntentReducer from "../set_hawk_intent_reducer";
import SetNameReducer from "../set_name_reducer";
import UpdateTransformReducer from "../update_transform_reducer";

export type JoinGameParams = __Infer<typeof JoinGameReducer>;
export type RespawnParams = __Infer<typeof RespawnReducer>;
export type SetHawkIntentParams = __Infer<typeof SetHawkIntentReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type UpdateTransformParams = __Infer<typeof UpdateTransformReducer>;

